config/routes.rb
GoalaraCom::Application.routes.draw do
  
  root :to => "articles#index"
  
  devise_for :users, :controllers => {:sessions => 'sessions'}

  resources :users

  resources :viewers

  resources :feeds

  resources :articles

  resources :organizations

  resources :teams
  
  resources :frontpage
  
  resources :comments
  
  resources :votes
  
  get "/comment-vote" => "comments#vote", :as => :comment_vote_path
  
  devise_scope :user do
  
    match "login" => "sessions#sign_in_and_redirect", :as => :new_user_session_remote 
    match "logout" => "sessions#destroy", :as => :destroy_user_session
    match "register" => "devise/registrations#new", :as => :new_user_registration
  end
  
  match "set_teams" => "articles#set_teams"
  
  match "/navigate" => "articles#fetch"
  
  match "/news/:team_name" => "articles#show"
  match "/news" => "articles#show", :as => :navigator
  
  match "/application.manifest" => Rails::Offline
  
  match "/feed" => "articles#rss"
  
  match "/help" => "pages#help"
  
  
  

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  
  has_many  :articles
  
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.xml
  def index
    @feeds = Feed.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.xml
  def show
    @feed = Feed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.xml
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.xml
  def create
    @feed = Feed.new(params[:feed])

    respond_to do |format|
      if @feed.save
        format.html { redirect_to(@feed, :notice => 'Feed was successfully created.') }
        format.xml  { render :xml => @feed, :status => :created, :location => @feed }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.xml
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to(@feed, :notice => 'Feed was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.xml
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to(feeds_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :feed_url %><br />
    <%= f.text_field :feed_url %>
  </div>
  <div class="field">
    <%= f.label :site_name %><br />
    <%= f.text_field :site_name %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br />
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :site_logo %><br />
    <%= f.text_field :site_logo %>
  </div>
	<div class="field">
    <%= f.label :content_unique_div %><br />
    <%= f.text_field :content_unique_div %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/_form.html.haml
= form_for(@feed) do |f|
  - if @feed.errors.any?
    #error_explanation
      %h2
        = pluralize(@feed.errors.count, "error")
        prohibited this feed from being saved:
      %ul
        - @feed.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :feed_url
    %br/
    = f.text_field :feed_url
  .field
    = f.label :site_name
    %br/
    = f.text_field :site_name
  .field
    = f.label :site_url
    %br/
    = f.text_field :site_url
  .field
    = f.label :site_logo
    %br/
    = f.text_field :site_logo
  .field
    = f.label :content_unique_div
    %br/
    = f.text_field :content_unique_div
  .actions
    = f.submit

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/edit.html.haml
%h1 Editing feed
= render 'form'
= link_to 'Show', @feed
|
\#{link_to 'Back', feeds_path}

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<table>
  <tr>
    <th>Feed url</th>
    <th>Site name</th>
    <th>Site url</th>
    <th>Site logo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feeds.each do |feed| %>
  <tr>
    <td><%= feed.feed_url %></td>
    <td><%= feed.site_name %></td>
    <td><%= feed.site_url %></td>
    <td><%= feed.site_logo %></td>
	<td><%= feed.content_unique_div %></td>	
    <td><%= link_to 'Show', feed %></td>
    <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
    <td><%= link_to 'Destroy', feed, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/index.html.haml
%h1 Listing feeds
%table
  %tr
    %th Feed url
    %th Site name
    %th Site url
    %th Site logo
    %th
    %th
    %th
  - @feeds.each do |feed|
    %tr
      %td= feed.feed_url
      %td= feed.site_name
      %td= feed.site_url
      %td= feed.site_logo
      %td= feed.content_unique_div
      %td= link_to 'Show', feed
      %td= link_to 'Edit', edit_feed_path(feed)
      %td= link_to 'Destroy', feed, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Feed', new_feed_path

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/new.html.haml
%h1 New feed
= render 'form'
= link_to 'Back', feeds_path

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Feed url:</b>
  <%= @feed.feed_url %>
</p>

<p>
  <b>Site name:</b>
  <%= @feed.site_name %>
</p>

<p>
  <b>Site url:</b>
  <%= @feed.site_url %>
</p>

<p>
  <b>Site logo:</b>
  <%= @feed.site_logo %>
</p>

<p>
  <b>Content unique div:</b>
  <%= @feed.content_unique_div %>
</p>


<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.haml
%p#notice= notice
%p
  %b Feed url:
  = @feed.feed_url
%p
  %b Site name:
  = @feed.site_name
%p
  %b Site url:
  = @feed.site_url
%p
  %b Site logo:
  = @feed.site_logo
%p
  %b Content unique div:
  = @feed.content_unique_div
= link_to 'Edit', edit_feed_path(@feed)
|
\#{link_to 'Back', feeds_path}