config/routes.rb
GoalaraCom::Application.routes.draw do
  
  root :to => "articles#index"
  
  devise_for :users, :controllers => {:sessions => 'sessions'}

  resources :users

  resources :viewers

  resources :feeds

  resources :articles

  resources :organizations

  resources :teams
  
  resources :frontpage
  
  resources :comments
  
  resources :votes
  
  get "/comment-vote" => "comments#vote", :as => :comment_vote_path
  
  devise_scope :user do
  
    match "login" => "sessions#sign_in_and_redirect", :as => :new_user_session_remote 
    match "logout" => "sessions#destroy", :as => :destroy_user_session
    match "register" => "devise/registrations#new", :as => :new_user_registration
  end
  
  match "set_teams" => "articles#set_teams"
  
  match "/navigate" => "articles#fetch"
  
  match "/news/:team_name" => "articles#show"
  match "/news" => "articles#show", :as => :navigator
  
  match "/application.manifest" => Rails::Offline
  
  match "/feed" => "articles#rss"
  
  match "/help" => "pages#help"
  
  
  

end

app/models/article.rb
require 'open-uri'
require 'paperclip'


class Article < ActiveRecord::Base
  
  self.per_page = 24
  
  belongs_to :feed
  belongs_to :organization
  has_and_belongs_to_many :team
  
  is_impressionable
  
  has_many :comments

  acts_as_commentable

  time = Time.new
  # Paperclip.options[:command_path] = "/usr/local/bin/"
  has_attached_file :image, :styles => {:thumb => "150x150#", :medium => "300x300#", :original => "600x600>"}
                    # :path => ":rails_root/public/articles/images/" + time.month.to_s() + "-" + time.year.to_s() + "/:id/:style/:filename"
  
  # validates_attachment_content_type :image, :content_type => ["image/jpeg", "image/pjpeg", "image/png", "image/x-png", "image/gif"]
  
  
  scope :belongs_to_team, lambda { |*team_id|
    unless team_id.first.nil?
      { :include => :team, :conditions =>
        ["teams.id = ?", team_id]
      }
    end
  }
  
  scope :has_team, lambda {
      { :include => :team, :conditions =>
        ["teams.id is not null"]
      }
  }
  
  scope :today_or_yesterday, lambda { 
    where("articles.created_at IS NOT NULL AND date(articles.created_at) >= ?", Date.yesterday)
  }
  
  
  scope :published_since, lambda { |ago|
    where("articles.created_at >= ?", ago)
  }
  
  scope :order_by, lambda { |*args| {:order => (args.first || 'id') } }
  scope :filter_by, lambda { |*args| {:conditions => (args.second.nil? || args.second.empty?) ? nil : [args.first + " = ?", args.second]} }
  
  def self.get_articles(params)
    if params[:team_id] == "all"
      params[:team_id] = nil
    end
    
    case params[:order_by]
    when 'popular'
      return Article.has_team.
                     today_or_yesterday.
                     belongs_to_team(params[:team_id]).
                     paginate(:page => params[:page]).
                     sort{ |u| -u.impressionist_count }

    
    # TODO ===  Sort by:  {number of comments}
    #when 'commented'
      #
      # @articles = Article.belongs_to_team(params[:team_id]).all(:select=> "articles.*, COUNT(articles.id) AS comments_count",
      #                                 :joins => :comments, 
      #                                 :group => "articles.id", 
      #                                 :order => "comments_count")
        
    else #sort by date
      return Article.has_team.
                     today_or_yesterday.
                     belongs_to_team(params[:team_id]).
                     order_by("articles.id").
                     paginate(:page => params[:page])
                     
    end
    
  end
  
  def self.update_feeds() 
    the_feeds = Feed.find(:all)
    the_feeds.each do |this_feed|
      feedzir = Feedzirra::Feed.fetch_and_parse(this_feed.feed_url)  
      feedzir.entries.each do |entry|  
        unless exists? :url => entry.url
          
          if entry.url == this_feed.feed_url
            next
          end
          
          parsed = parse_div_content2(
              entry.url, 
              { 'content' => this_feed.content_unique_div, 
                'category' => this_feed.category_unique_div, 
                'image' => this_feed.image_unique_div
              },
              this_feed.site_url
              )
          
                        
          create!(  
            :title          => entry.title,  
            :summary        => entry.summary,
            :content        => parsed["content"],
            :category       => parsed["category"],
            :url            => entry.url,
            :published_at   => entry.published,  
            :guid           => entry.id,
            :feed_id        => this_feed.id
          )
          # calculates tf-idf content and stores into Article.tf_idf_content
          calculate_tf_idf
          
          just_created = Article.last
          
          #TODO: uncomment the line below!!!
          tag_team_to_article_bayes(just_created)
          
          just_created.image_from_url(parsed["image"])
          if !parsed["image"].nil?
            
          end
        end  
      end
    end
  end
  
  
  def self.parse_div_content(url, div)
    puts url
    Scraper::Base.parser :html_parser
    
    scraper = Scraper.define do
      array :items
      process div, :div_content => :text
      result :div_content
    end

    uri = URI.parse(url)

    t = HTMLEntities.new.decode scraper.scrape(uri).force_encoding('UTF-8')

    return t
    #return Iconv.conv('utf-8//IGNORE', 'utf-8', scraper.scrape(uri) ) 
  end
  
  def self.parse_div_content2(url, div, site_url)
    doc = Nokogiri::HTML(open(url))
    
    parsed = {}
    #content div
    if !div["content"].nil?
      parsed["content"] = doc.css(div["content"]).first.content
    else
      parsed["content"] = nil
    end

    #category div
    if !div["category"].nil?
      element = doc.css(div["category"])
      if !element.first.nil?
        parsed["category"] = element.first.content
      end
    else
      parsed["category"] = nil
    end
    
    #image div
    parsed["image"] = find_biggest_image(doc, site_url)
    
    # if !div["image"].nil?
    #       image_html = doc.css(div["image"] + " > img").first
    #       if !image_html.nil?
    #         parsed["image"] = get_image_src_from_text(image_html.to_html)
    #       end
    #     end
    #     if div["image"].nil? || image_html.nil?
    #       parsed["image"] = find_biggest_image(doc, feed_url)
    #     end
    
  
    return parsed
    
  end
  
  
  def self.tag_team_to_article (data)
    
    articles = Article.has_team
    
    if !articles.empty?
      lsi = Classifier::LSI.new
      articles.each{ |a|
        teams = a.team.collect(&:name)
        lsi.add_item a.tf_idf_content, *teams
      }
      result = lsi.classify data
      
      return Team.find_by_name(result.to_s).id
    else
      return nil
    end
  end
  
  
  def self.tag_team_to_article_bayes(this_article)
    
    # grab stored bayes object
    bayes = ObjectStash.load Rails.root.join('config', 'bayes_classification.stash')

    if !bayes.nil?
      
      #Classify
      result = bayes.classifications this_article.tf_idf_content
      result.sort_by{|k,v| -v}
      matched_teams = [ Team.find_by_name(result.keys[0].to_s).id,
                        Team.find_by_name(result.keys[1].to_s).id]

      this_article.team_ids = matched_teams

    end
    
  end
  
  def self.train
    
    articles = Article.has_team
    
    if !articles.empty?
      bayes = Classifier::Bayes.new
      
      Team.all.each do |team|
        bayes.add_category team.name
      end
      
      #train
      articles.each{ |a|
        a.team.each do |t|
          bayes.train t.name, a.tf_idf_content
        end
      }
      
      #store bayes object
      ObjectStash.store bayes, Rails.root.join('config', 'bayes_classification.stash'), {:gzip => false}
    end
  end
  
  
  
  def self.calculate_tf_idf
    articles = self.find(:all)
    reduced = Array.new
    articles.each{ |x|
      all_info = x.title + ' ' + x.title + ' ' + x.content # give a bit more boost to title

      # remove html tags
      all_info = CGI::unescapeHTML(all_info.gsub(/<\/?[^>]*>/, ""))
      
      reduced.push(all_info
        .greeklish.gsub(/[^a-z ]/i, ' ').gsub!(/ +/, ' ').downcase.split(' '))
    }
    
    a = TfIdf.new(reduced)
    tf_idf = a.tf_idf
    
    i = 0;
    tf_idf.each { |doc|
      id = articles[i].id
      result = ''
      doc.each { |term, freq|
        if Float(freq) > 0.004
          result = result + ' ' + term
        end
      }
      Article.update(id, {:tf_idf_content => result})
      i+=1
    }
    
  end
  
  
  def previous(offset = 0)    
      self.class.first(:conditions => ['id < ?', self.id], :limit => 1, :offset => offset, :order => "id DESC")
  end

  def next(offset = 0)
    self.class.first(:conditions => ['id > ?', self.id], :limit => 1, :offset => offset, :order => "id ASC")
  end
  

  def image_from_url(url)
    remote_image = open(url)
    
    def remote_image.original_filename;base_uri.path.split('/').last; end
    
    update_attribute(:image, remote_image)

  end

  def self.get_image_src_from_text(text)
    text =~ /src=\"([^\"\s]+)\"/
    s = "#{$1}"
  end
  
  def self.find_biggest_image(doc, url)
    objective_function = 0
    main_image_url = nil
    doc.css("img").each do |img|
      src = add_site_url_to_link(img.attributes["src"].value, url)
      dim = FastImage.size(URI.encode(src))
      
      
      if !dim.nil? 
        aspect_ratio_gaussian = 2.72**(-( (dim[0]/dim[1]-1)**2 ) / 0.7)
        if dim[0]/dim[1] > 2.5 || dim[1]/dim[0] > 2.5 #probably an ad
          next
        end
    
        if src.index(url) == nil #means is coming from other domain
          next
        end
        
        width_height = dim[0] + dim[1]
        if width_height > objective_function
          objective_function = width_height
          main_image_url = src
        end
      end
      
    end
    puts main_image_url
    main_image_url
    
  end
  
  def self.add_site_url_to_link(link, site_url)
    if link.index("http:") == nil
      link = site_url + link.gsub(/^\//, "")
    end
    
    link
    
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  skip_authorization_check  :only => [:index, :show, :rss, :fetch, :set_teams] 
  
  include ApplicationHelper
  
  impressionist :actions=>[:show,:fetch]
  
  respond_to :json, :xml, :html
  
  # GET /articles
  # GET /articles.xml
  def index
    
    @articles = Article.get_articles(params)
    
    @teams = Team.all
    @organizations = Organization.all
    
    if request.xhr?
      request.format = :json
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  {render :partial => "list.html.haml"}
      format.json {
        @list = render_to_string(:partial => "/articles/list.html.haml")
        @pagination_links = render_to_string(:partial => "/articles/pagination_links.html.haml")
        render :json => { :data => @list, :pages => @pagination_links }
      }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
 
    respond_to do |format|
      format.html {
        @teams = Team.all
        # TODO: get only articles in the last 2 days    
        @articles = Article.get_articles(params)
        render :layout => 'navigator'
      }
      format.xml  { 
        @article = Article.find(params[:id], :include => :team)
        render :xml => @article.team_ids 
      }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new
 
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])
    
    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
  
  def set_teams
    @articles = Article.where(:validated => false)
    @teams = Team.all
    
    if !params[:team_ids].nil?
      a = Article.find(params[:id])
      a.team_ids = params[:team_ids]
      a.validated = true
      a.save
    end
    
    if request.xhr?
      request.format = :json
    end
    
    response= {:head => "ok"}
    respond_to do |format|
      format.html # set_teams.html.haml
      format.xml  { head :ok }
      format.json  {  render :json  => response.to_json  }
    end
  end
  
  def rss
    @articles = Article.find(:all, :order => "id DESC", :limit => 30)
    render :layout => false
    response.headers["Content-Type"] = "application/xml; charset=utf-8"
  end
  
  
  
  def fetch
    if params[:status] == 'team_change' #then ignore article_id
      @article = Article.belongs_to_team(params[:team_id]).first
    elsif params[:team_id] != 'all'
      @article = Article.find(:first, :conditions => {:id => params[:id], :team_id => params[:team_id] } )
    else
      @article = Article.find_by_id(params[:id])
    end
    
    @teams = Team.all
    
    if @article
      @prev_article_hash = @article.previous == nil ? '' : @article.previous.id.to_s() + '/' + remove_http(@article.previous.url) + '/tid_' + params[:team_id]
      @next_article_hash = @article.next == nil ? '' : @article.next.id.to_s() + '/' + remove_http(@article.next.url) + '/tid_' + params[:team_id]
      @comments = @article.comment_threads.all
      
      @comments_list = render_to_string :partial => "articles/comments_list.html.haml"
      @navigation_buttons = render_to_string :partial => "articles/navigation_buttons.html.haml"
      @iframe =   render_to_string :partial => "articles/article-iframe.html.haml"
      
      response = {
        'article_id'          => @article.id,
        'iframe'              => @iframe,
        'article_title'       => @article.title,
        'comments'            => @comments_list,
        'navigation_buttons'  => @navigation_buttons,
        'total_comments'      => @comments.size,
        'next_article_hash'   => @next_article_hash,
        'prev_article_hash'   => @prev_article_hash
      }
    else
       @main = render_to_string :partial => "articles/no_article.html.haml"
       response = { 
         'error' => 'no_results',
         'main'  => @main
         }
    end

    if user_signed_in?
      response['signedin'] = 'true';
    else
      response['signedin'] = 'false';
    end

    if request.xhr?
      request.format = :json
    end
    
    respond_to do |format|
      format.json { render :json  => response.to_json }
    end
    
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper

end

app/views/articles/_comment_form.html.haml
.commentAddForm.clearfix.secondary
  .signed-in
    %label.formItemLabel
      = form_tag(comments_path, :method => "post", :remote => true, :id => "add_comment") do
        %textarea{:cols => "", :name => "body", :rows => ""}
        %input{:name => "commentable_id", :type => "hidden", :value => "#{!@article.nil? ? '@article.id' : ''}" }    
        %input{:name => "user_id", :type => "hidden", :value => "#{current_user.id if current_user}"}
        %input{:name => "commentable_type", :type => "hidden", :value => "Article"}
        - if !user_signed_in?
          .formItemLine.signed-out
          
            %p.signin
              Για να σχολιάσετε,
              = link_to 'συνδεθείτε', "#", :class => "sign_panel"
              ή 
              = link_to 'δημιουργήστε λογαριασμό',  "#", :class => "sign_panel"
        - else
          %span.button.primary
            %span
              %input.submit{:name => "submit", :type => "submit", :value => "Submit"}
          %p.charactersUsed
            Characters remaining:
            %em.commentOK 2000

app/views/articles/_comments_list.html.haml
- @comments.each do |comment|
  %li.comment
    .comment
      = link_to image_tag(get_user_avatar(comment.user), :alt => comment.user.fullname + ' image', :class => "profile"), user_path(comment.user_id), :target => "_blank", :class => "profile_picture"
      .commentHeader
        %h4
          = link_to comment.user.fullname, user_path(comment.user_id), :target => "_blank"
          %span.user_team
            = user_team_logo(comment.user)
        %ul.actions
          - votes = comment.plusminus
          - if votes > 0
            %li.score.positive 
              = "+" + votes.to_s()
          - elsif votes < 0
            %li.score.negative
              = votes
          - else
            %li.score
              = votes
          %li.vote
            - if current_user.nil?
              = link_to "",  "/", :class => "cantvote voteUp"
              = link_to "",  "/", :class => "cantvote voteDown" 
            - else
              = link_to "",  new_vote_path(:user_id => current_user.id, :comment_id => comment.id, :vote => "up"), :remote => true, :class => "voteUp voting"
              = link_to "",  new_vote_path(:user_id => current_user.id, :comment_id => comment.id, :vote => "down"), :remote => true, :class => "voteDown voting"
          %li
            / %span.edit
            /              %a.edit Edit
            /              %a.delete Delete
            /              %a.reply Reply
      .flairWrap
      .commentBody
        %span.date 
          = comment.created_at.to_s(:friendly)
        %span.commentText 
          = comment.body
        / %a.flag.tip{:href => "#"}

app/views/articles/_form.html.haml
/
  <haml:loud> semantic_form_for(@article) do |f| </haml:loud><haml:block>
  <haml:silent>   if @article.errors.any?
  </haml:silent><haml:block>    <div id="error_explanation">
  <h2><haml:loud> pluralize(@article.errors.count, &quot;error&quot;) </haml:loud> prohibited this article from being saved:</h2>
  
  <ul>
  <haml:silent>       @article.errors.full_messages.each do |msg|
  </haml:silent><haml:block>        <li><haml:loud> msg </haml:loud></li>
  </haml:block>      </ul>
  </div>
  </haml:block>
  <div class="field">
  <haml:loud> f.label :title </haml:loud><br />
  <haml:loud> f.text_field :title </haml:loud>
  </div>
  <div class="field">
  <haml:loud> f.label :summary </haml:loud><br />
  <haml:loud> f.text_area :summary </haml:loud>
  </div>
  <div class="field">
  <haml:loud> f.label :content </haml:loud><br />
  <haml:loud> f.text_area :content </haml:loud>
  </div>
  <div class="field">
  <haml:loud> f.label :url </haml:loud><br />
  <haml:loud> f.text_field :url </haml:loud>
  </div>
  <div class="field">
  <haml:loud> f.label :published_at </haml:loud><br />
  <haml:loud> f.text_field :published_at </haml:loud>
  </div>
  <div class="field">
  <haml:loud> f.label :guid </haml:loud><br />
  <haml:loud> f.text_field :guid </haml:loud>
  </div>
  <div class="actions">
  <haml:loud> f.submit </haml:loud>
  </div>
  </haml:block>
= semantic_form_for @article do |form|
  = form.inputs
  = form.buttons

app/views/articles/_list.html.haml
- @articles.each do |article|
  %li.an_article{:"data-id" => "#{article.id}"}
    %a{:href => "#{article_url(article)}", :class => 'article_image'}
      = article_image(article, article.feed.site_logo)
      %div.description
        %div.description_content
          = article.title
          %div.abstract{:style => "display:none"}
            = shorten(article.summary)

app/views/articles/_no_article.html.haml
#inner
  %h1.title
    Δεν βρέθηκαν άρθρα για την ομάδα που επιλέξατε.

  %h2.subtitle
    Δείτε τα άρθρα για
    %a#view_all_teams.select_new_team{ :"data-teamID" => "all"}
      όλες τις ομάδες
    ή επιλέξτε μια ομάδα:
  
  %ul.list_teams_articles
    - @teams.each do |team|
      %li{:id => "tid_#{team.id}" }
        %span.image
          = image_tag(team.logo_image, :class => 'list_image')
        %a.select_new_team.name{:href => "", onclick => "return false;", :href => "#", :"data-teamID" => "#{team.id}"}
          = translate(team.name)
        %div.count
          = team.article.size.to_s() + " άρθρα"

app/views/articles/_pagination_links.html.haml
= will_paginate @articles

app/views/articles/edit.html.haml
%h1 Editing article
= render 'form'
= link_to 'Show', @article
|
\#{link_to 'Back', articles_path}

app/views/articles/fetch.json.erb
{
    sidebox: <%= @sidebox %>,
    main: <%= @main %>,
    topbar: <%= @topbar %>
}

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Summary</th>
    <th>Content</th>
    <th>Url</th>
    <th>Published at</th>
    <th>Guid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.summary %></td>
    <td><%= article.content %></td>
    <td><%= article.url %></td>
    <td><%= article.published_at %></td>
    <td><%= article.guid %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/index.html.haml
= title "Παίρνεις την μπάλα μαζί σου!"

%ul.list_teams
  - @teams.each do |team|
    %li.floatleft
      = team_logo(team.logo_image)
%div.clearfix
%div{:style => "position: static;", :class => "local"}
  %h3 Ταξινόμηση κατά:
  %ul{:id => 'order_by'}
    %li 
      = link_to "Νεότερα", request.url, :class => "selected", :"data-value" => 'newest'
    %li 
      = link_to "Δημοφιλέστερα", request.url,  :"data-value" => 'popular'
    / %li 
    /       = link_to "Περισσότερα σχόλια", request.url, :"data-value" => 'commented'
  %h3 Εμφάνιση άρθρων για:
  %ul{:id => 'filter_by'}
    %li
      = link_to 'Όλες τις ομάδες', request.url,  :"data-value" => 'all', :class => "selected"
    - @teams.each do |team|
      %li 
        = link_to translate(team.name), request.url,  :"data-value" => team.id
  / %h3 Filter by Organization
  /   %ul{:id => 'filter_by'}
  /     %li
  /       = link_to 'All', request.url, :onclick => 'return false;', :"data-value" => 'all'
  /     - @organizations.each do |organization|
  /       %li 
  /         = link_to organization.name, request.url, :onclick => 'return false;', :"data-value" => organization.id        
  %div.loading{:style => "display:none"}
    = image_tag("ajax-loader.gif")


%div{:class => "browser"}
  %ul.articles_list#articles_list.clearfix
    = render :partial => "list"
  
  %div.loading{:style => "display:none"}
    = image_tag("ajax-loader.gif", :class => "center")
    
  %div#pagination_links.hidden
    = render :partial => "pagination_links"
  
  %ul#shuffler.hidden

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/new.html.haml
%h1 New article
= render 'form'
= link_to 'Back', articles_path

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Summary:</b>
  <%= @article.summary %>
</p>

<p>
  <b>Content:</b>
  <%= @article.content %>
</p>

<p>
  <b>Url:</b>
  <%= @article.url %>
</p>

<p>
  <b>Published at:</b>
  <%= @article.published_at %>
</p>

<p>
  <b>Guid:</b>
  <%= @article.guid %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.haml
#topbar
  #floatingbar
    = render :partial => "topbar"
#view_content

  // Begin sidebox
  #sidebox
    #header_info
      .logo_wrapper.floatleft
        = link_to image_tag("/images/logo_small.png",  :alt =>  'Goalara.com'), "/"
      .header_comments.floatright
        %strong 
          - if !@comments.nil?
            %span 
              = @comments.size.to_s
            Σχόλια
          - else
            %span
            Σχόλια
    %div{:style => "clear:both"}
    #conversation
      #discussion.silverBorderPanel
        .comment-container
          / #comments_loading.loader_img{:style => "display:none"}
          /             = image_tag "loader.gif", :class => 'loader'
          %ul#commentList-30.l-0
            // Comments go here
            
    = render :partial => "comment_form"
           
    
 
  #article_viewer
    / .loader_img{:style => "display:none"}
    /       = image_tag "loader.gif", :class => 'loader'
    %div#no_article
    %div#main_frame.hidden
      = render :partial => "article-iframe"

= render :partial => "articles/sync_modal_window.html.haml"