config/routes.rb
GoalaraCom::Application.routes.draw do
  
  root :to => "articles#index"
  
  devise_for :users, :controllers => {:sessions => 'sessions'}

  resources :users

  resources :viewers

  resources :feeds

  resources :articles

  resources :organizations

  resources :teams
  
  resources :frontpage
  
  resources :comments
  
  resources :votes
  
  get "/comment-vote" => "comments#vote", :as => :comment_vote_path
  
  devise_scope :user do
  
    match "login" => "sessions#sign_in_and_redirect", :as => :new_user_session_remote 
    match "logout" => "sessions#destroy", :as => :destroy_user_session
    match "register" => "devise/registrations#new", :as => :new_user_registration
  end
  
  match "set_teams" => "articles#set_teams"
  
  match "/navigate" => "articles#fetch"
  
  match "/news/:team_name" => "articles#show"
  match "/news" => "articles#show", :as => :navigator
  
  match "/application.manifest" => Rails::Offline
  
  match "/feed" => "articles#rss"
  
  match "/help" => "pages#help"
  
  
  

end

app/models/viewer.rb
class Viewer < ActiveRecord::Base
end

app/controllers/viewers_controller.rb
class ViewersController < ApplicationController
  include ApplicationHelper
  
  respond_to :json
  
  # GET /viewers
  # GET /viewers.xml
  def index
    @teams = Team.all
    # TODO: get only articles in the last 2 days    
    @articles = Article.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @viewers }
    end
  end

  # GET /viewers/1
  # GET /viewers/1.xml
  def show
    # @article = Article.find_by_id(params[:id])
    #     @prev_article = @article.previous == nil ? 0 : @article.previous
    #     @next_article = @article.next == nil ? 0 : @article.next
    #     @comments = @article.comment_threads.all
    #     @teams = Team.all
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @viewer }
    end
  end

  # GET /viewers/new
  # GET /viewers/new.xml
  def new
    @viewer = Viewer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @viewer }
    end
  end

  # GET /viewers/1/edit
  def edit
    @viewer = Viewer.find(params[:id])
  end

  # POST /viewers
  # POST /viewers.xml
  def create
    @viewer = Viewer.new(params[:viewer])

    respond_to do |format|
      if @viewer.save
        format.html { redirect_to(@viewer, :notice => 'Viewer was successfully created.') }
        format.xml  { render :xml => @viewer, :status => :created, :location => @viewer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @viewer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /viewers/1
  # PUT /viewers/1.xml
  def update
    @viewer = Viewer.find(params[:id])

    respond_to do |format|
      if @viewer.update_attributes(params[:viewer])
        format.html { redirect_to(@viewer, :notice => 'Viewer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @viewer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /viewers/1
  # DELETE /viewers/1.xml
  def destroy
    @viewer = Viewer.find(params[:id])
    @viewer.destroy

    respond_to do |format|
      format.html { redirect_to(viewers_url) }
      format.xml  { head :ok }
    end
  end
  
  def fetch
    if params[:status] == 'team_change' #then ignore article_id
      @article = Article.find_by_team_id(params[:team_id])
    elsif params[:team_id] != 'all'
      @article = Article.find(:first, :conditions => {:id => params[:id], :team_id => params[:team_id] } )
    else
      @article = Article.find_by_id(params[:id])
    end
    
    @teams = Team.all
    
    if @article
      @prev_article_hash = @article.previous == nil ? '' : @article.previous.id.to_s() + '/' + remove_http(@article.previous.url) + '/tid_' + params[:team_id]
      @next_article_hash = @article.next == nil ? '' : @article.next.id.to_s() + '/' + remove_http(@article.next.url) + '/tid_' + params[:team_id]
      @comments = @article.comment_threads.all
      
      @comments_list = render_to_string :partial => "viewers/comments_list.html.haml"
      @navigation_buttons = render_to_string :partial => "viewers/navigation_buttons.html.haml"
      @iframe =   render_to_string :partial => "viewers/article-iframe.html.haml"
      
      response = {
        'article_id'          => @article.id,
        'iframe'              => @iframe,
        'article_title'       => @article.title,
        'comments'            => @comments_list,
        'navigation_buttons'  => @navigation_buttons,
        'total_comments'      => @comments.size,
        'next_article_hash'   => @next_article_hash,
        'prev_article_hash'   => @prev_article_hash
      }
    else
       @main = render_to_string :partial => "viewers/no_article.html.haml"
       response = { 
         'error' => 'no_results',
         'main'  => @main
         }
    end

    if user_signed_in?
      response['signedin'] = 'true';
    else
      response['signedin'] = 'false';
    end

    if request.xhr?
      request.format = :json
    end
    
    respond_to do |format|
      format.json { render :json  => response.to_json }
    end
    
  end
end

app/helpers/viewers_helper.rb
module ViewersHelper
end

app/views/viewers/_comment_form.html.haml
.commentAddForm.clearfix.secondary
  .signed-in
    %label.formItemLabel
      = form_tag(comments_path, :method => "post", :remote => true, :id => "add_comment") do
        %textarea{:cols => "", :name => "body", :rows => ""}
        - if !@article.nil?
          %input{:name => "commentable_id", :type => "hidden", :value => "#{@article.id}" }    
        - else
          %input{:name => "commentable_id", :type => "hidden", :value => "" } 
        %input{:name => "user_id", :type => "hidden", :value => "#{current_user.id if current_user}"}
        %input{:name => "commentable_type", :type => "hidden", :value => "Article"}
        - if !user_signed_in?
          .formItemLine.signed-out
          
            %p.signin
              Για να σχολιάσετε,
              = link_to 'συνδεθείτε', :class => "sign_in"
              ή 
              = link_to 'δημιουργήστε λογαριασμό', new_user_registration_path
        - else
          %span.button.primary
            %span
              %input.submit{:name => "submit", :type => "submit", :value => "Submit"}
          %p.charactersUsed
            Characters remaining:
            %em.commentOK 2000

app/views/viewers/_comments_list.html.haml
- @comments.each do |comment|
  %li#id.comment
    .comment
      = link_to image_tag(get_user_avatar(comment.user), :alt => comment.user.fullname + ' image', :class => "profile"), user_path(comment.user_id), :target => "_blank", :class => "profile_picture"
      .commentHeader
        %h4
          = link_to comment.user.fullname, user_path(comment.user_id), :target => "_blank"
          %span.user_team
            = user_team_logo(comment.user)
        %ul.actions
          - votes = comment.plusminus
          - if votes > 0
            %li.score.positive 
              = "+" + votes.to_s()
          - elsif votes < 0
            %li.score.negative
              = votes
          - else
            %li.score
              = votes
          %li.vote
            - if current_user.nil?
              = link_to "",  "/", :remote => true, :class => "voteUp"
              = link_to "",  "/", :remote => true, :class => "voteDown" 
            - else
              = link_to "",  new_vote_path(:user_id => current_user.id, :comment_id => comment.id, :vote => "up"), :remote => true, :class => "voteUp voting"
              = link_to "",  new_vote_path(:user_id => current_user.id, :comment_id => comment.id, :vote => "down"), :remote => true, :class => "voteDown voting"
          %li
            / %span.edit
            /              %a.edit Edit
            /              %a.delete Delete
            /              %a.reply Reply
      .flairWrap
      .commentBody
        %span.date 
          = comment.created_at.to_s(:friendly)
        %span.commentText 
          = comment.body
        %a.flag.tip{:href => "#"}

app/views/viewers/_form.html.erb
<%= semantic_form_for @viewer do |f| %>
  <%= f.inputs do %>
  <% end %>

  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>

app/views/viewers/_navigation_buttons.html.haml
%li
  / Begin Navigate Previous
  = link_to "", '/goalara#' + @prev_article_hash , :onclick => "return false;"  , :class => "navigate_buttons", :id => "previous_article"
%li
  / Begin Navigate Previous
  = link_to "", '/goalara#' + @next_article_hash , :onclick => "return false;"  , :class => "navigate_buttons", :id => "next_article"

app/views/viewers/_sidebox.html.haml
#header_info
  .logo_wrapper.floatleft
    = link_to image_tag("/images/logo_small.png",  :alt =>  'Goalara.com'), "/"
  .header_comments.floatright
    %strong 
      = @comments.size.to_s + ' Σχόλια'
%div{:style => "clear:both"}
#conversation
  #discussion.silverBorderPanel
    .comment-container
      %ul#commentList-30.l-0
        - @comments.each do |comment|
          %li#id.comment
            .comment
              = link_to image_tag("/images/users/" + comment.user.avatar, :alt => comment.user.fullname + ' image'), user_path(comment.user_id), :target => "_blank"
              .commentHeader
                %h4
                  = link_to comment.user.fullname, user_path(comment.user_id), :target => "_blank"
                %ul.actions
                  %li.score 0
                  %li.vote
                    %a.voteUp
                  %li
                    / %span.edit
                    /              %a.edit Edit
                    /              %a.delete Delete
                    /              %a.reply Reply
              .flairWrap
              .commentBody
                %span.date.fresh 
                  = comment.created_at.to_s(:friendly)
                %span.commentText 
                  = comment.body
                %a.flag.tip{:href => "#"}
                
.commentAddForm.clearfix.secondary
  .formItemLine.signed-out
    %p.signin
      %a.signin{:href => "http://www.ted.com/users/signin"} Sign in to add comments
      or
      %a{:href => "http://www.ted.com/pages/view/id/114"} Join (It's free and fast!)
  .signed-in
    %label.formItemLabel
    %form{:action => "", :method => "post"}
      %textarea{:cols => "", :name => "newComment", :rows => ""}
      %span.button.primary
        %span
          %input.submit{:name => "submit", :type => "submit", :value => "Submit"}
      %p.charactersUsed
        Characters remaining:
        %em.commentOK 2000

app/views/viewers/_sync_modal_window.html.haml
#osx-modal-content
  #osx-modal-title
    Συγχρονισμός των άρθρων μου
    // title goes here
  #osx-modal-data
    .content
      %div.alert
      Παρακαλούμε μην διακόψετε την διαδικασία συγχρονισμού.
      %br
      %br
      = image_tag("ajax-loader.gif", {:style => "margin:auto"})
      %br
      Ολοκληρώθηκε ο συγχρονισμός:&nbsp;&nbsp; 
      %span.progress
        %span#sync_done{:style => "color:green"}
          1
        &nbsp;/&nbsp;
        %span#articles_total
          = @articles.size
        άρθρων
  
  #sync_is_complete_content.hidden
    %div
      O συγχρονισμός των άρθρων έχει ολοκληρωθεί με επιτυχία. Όλα τα άρθρα είναι διαθέσιμα offline!
    %button.simplemodal-close
      OK
/ #modal_windows_content{:style => "display:none"}
/   %a.osx
/   #window1
/     .content
/       %form#sync_team
/         %label{:for => "email"} Επιλέξτε ομάδα:
/         = select("team", "id", [["Eπιλέξτε", 0]] + @teams.map {|u| [u.name,u.id]}, :selected => '0')
/         %br
/         %br
/         %br
/         %br
/         %br
/       #buttons
/         %button.step2.floatright
/           Επόμενο 
/   #window2
/     .content
/       #sync_message
/         Πατήστε το κουμπί για να γίνει συγχρονισμός των άρθρων της ομάδας: 
/         %span.selected_team
/       %button#start_sync
/         Εκκίνηση συγχρονισμού
/       #alert_message
/         Σημαντικό: Αφού πατήσετε το κουμπί ΜΗΝ διακόψετε την διαδικασία συγχρονισμού. Παραμείνετε σε αυτή την σελίδα μέχρι να ολοκληρωθεί ο συγχρονισμός!
/       #buttons
/         %button.step1.floatleft
/           Προηγούμενο
/   #window3_success
/     .content
/       O συγχρονισμός των άρθρων έχει ολοκληρωθεί με επιτυχία. Όλα τα άρθρα της ομάδας 
/       %span.selected_team 
/       βρίσκονται 
/       %a.open_article_list 
/         στην λίστα των άρθρων σας
/       #buttons
/         %button.simplemodal-close.floatright
/           Κλείσιμο
/   #window3_fail
/     .content
/       Παρουσιάστηκε κάποιο σφάλμα κατά την διαδικασία συγχρονισμού. Παρακαλούμε δοκιμάστε αργότερα
/       #buttons
/         %button.simplemodal-close.floatright
/           Κλείσιμο
/ 

app/views/viewers/_topbar.html.haml
%div#panel
  %div#sync_window.floatleft
    %div.sync_info
      %h2
        Τα άρθρα μου
      %ul
        %li
          %div.label
            Αριθμός άρθρων:
          %div#total_articles.value
            = @articles.size
        %li
          %div.label
            Διαθέσιμα offline:
          %div#available_offline.value.zero
            0   
      %div.message
        Τα άρθρα που είναι διαθέσιμα offline είναι μαρκαρισμένα με το σύμβολο 
        = image_tag("available.png", {:width => "14", :height => "14", :style => "display:inline"})
        %p{:style => "margin-top: 10px"}
          Για να έχετε πρόσβαση σε όλα τα άρθρα όταν βρίσκεστε εκτός σύνδεσης (offline), πατήστε το πιο κάτω κουμπί συγχονισμού:
    %div.sync_button
      %button#start_sync.osx
        Συγχρονισμός άρθρων
  %div.wrapper
    %div.filter_list
      Εμφάνιση άρθρων για:
      = collection_select(:team, :id, @teams, :id, :name, options ={:prompt => "Όλες τις ομάδες"})
    %div.clearfix
    %ul.articles_list#articles_list
      - @articles.each do |article|
        %li.an_article{:"data-article-id" => "#{article.id}", :"data-team-id" => "#{!article.team.empty? ? article.team.first.id : ''}"}
          %div.details
            %ul
              %li.team
                - if !article.team.empty?
                  = image_tag(article.team.first.logo_image)
              %li.offline
              %li.date
                = article.created_at
          %a{:href => "#{article_url(article)}", :class => 'article_image'}
            = image_tag(article.image.url(:medium))
            %div.description
              %div.description_content
                = article.title
%ul.gallery
  %li.right_divider.login_part{:style => "width:200px;position:relative;padding-left:15px"}
    = render :partial => "user_top_panel"
  %li{:style => "width:70px"}
    / Begin Total comments
    %span.total_comments
      - if !@comments.nil?
        = @comments.size
  %li{:style => "width:100px"}
    / Begin Add to Favorites
    = link_to "", "#" , :onclick => "return false;", :class => "show_hide_articles"
  %li{:style => "width:100px;padding-top:24px"}
    / Begin Facebook Like
    #fb-root
    %script{:src => "http://connect.facebook.net/en_US/all.js#appId=267779433232955&xfbml=1"}
    %fb:like{:action => "like", :font => "", :href => request.url, :layout => "button_count", :send => "true", :show_faces => "true", :width => "450"}
  %li.show_current_team{:style => "width:284px;position:absolute; right:302px;bottom:0px"}
    / Begin Select Team
    %a{:onclick => "return false;", :class => "team_selector"}
      %span.image
        = image_tag("ball_xsmall.png")
      %span.name
        Όλες οι ομάδες
    %ul.team_dropbox{:style =>"display:none"}
      %li{:id => "tid_all", :"data-teamID" => "all" }
        %a{:onclick => "return false;"}
          %span.image
            = image_tag "ball_medium.jpg"
          %span.name
            Όλες οι ομάδες
      - @teams.each do |team|
        %li{:id => "tid_#{team.id}", :"data-teamID" => "#{team.id}" }
          %a{:onclick => "return false;"}
            %span.image
              = team_logo(team.logo_image, 'list_image')
            %span.name{:href => "#", :onclick => "return false;" }
              = team.name
          
%ul.gallery.navigation_buttons{:style => "position:absolute; bottom: 0px; right:20px"}
  - if !@navigation_buttons.nil?
    = @navigation_buttons

%input{:type => "hidden", :id => "sync_pointer", :value => 0}

:javascript
  total_articles_available = "#{@articles.size}"
  

app/views/viewers/_user_top_panel.html.haml
/ Begin Sign In 
- if user_signed_in?
  %div.user_avatar.floatleft
    = image_tag get_user_avatar(current_user)
  /  = get_team_logo(current_user.team) # TODO: implement the "user has team" functionality
  %div.user_name.floatleft
    = link_to current_user.fullname, user_path(current_user)
    = link_to "Sign out", destroy_user_session_path, :class => "small", :id => "signout"
- else 
  %a.sign_in{:href => "#"}
    Συνδεθείτε 
    %br 
    ή Δημιουργήστε λογαριασμό
  %fieldset#signin_menu
    #left_panel.floatleft
      %form#signin{:action => "#{new_user_session_path}", :method => "post"}
        %span.the_title Login with your Goalara.com account
        %label{:for => "email"} Email
        %input#email{:name => "user[email]", :tabindex => "4", :title => "email", :type => "text", :value => ""}
          %p
            %label{:for => "password"} Password
            %input#password{:name => "user[password]", :tabindex => "5", :title => "password", :type => "password", :value => ""}
          %p.remember
            %input#signin_submit{:tabindex => "6", :type => "submit", :value => "Sign in"}
              %input#remember{:name => "remember_me", :tabindex => "7", :type => "checkbox", :value => "1"}
                %label{:for => "remember"} Remember me
          %p.forgot
            %a#resend_password_link{:href => "#"} Forgot your password?
          %p.forgot-username
            %a#forgot_username_link{:href => "#", :title => "If you remember your password, try logging in with your email"} Forgot your username?
    #right_panel.floatleft
      %span.the_title or with your Facebook account
      = link_to image_tag("facebook_alt.png"), user_omniauth_authorize_path(:facebook)
    #doomed_panel.clearfix
    #bottom_panel.clearfix
      %h2.speech
        I don't have Facebook or an account at Goalara.com
        %a#create_account_link{:href => "#{new_user_registration_path}", :title => "If you remember your password, try logging in with your email"} Create an account at Goalara.com instantly

app/views/viewers/edit.html.erb
<h1>Editing viewer</h1>

<%= render 'form' %>

<%= link_to 'Show', @viewer %> |
<%= link_to 'Back', viewers_path %>

app/views/viewers/index.html.erb
<h1>Listing viewers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @viewers.each do |viewer| %>
  <tr>
    <td><%= link_to 'Show', viewer %></td>
    <td><%= link_to 'Edit', edit_viewer_path(viewer) %></td>
    <td><%= link_to 'Destroy', viewer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Viewer', new_viewer_path %>

app/views/viewers/index.html.haml
#topbar
  #floatingbar
    = render :partial => "topbar"
#view_content

  // Begin sidebox
  #sidebox
    #header_info
      .logo_wrapper.floatleft
        = link_to image_tag("/images/logo_small.png",  :alt =>  'Goalara.com'), "/"
      .header_comments.floatright
        %strong 
          - if !@comments.nil?
            %span 
              = @comments.size.to_s
            Σχόλια
          - else
            %span
            Σχόλια
    %div{:style => "clear:both"}
    #conversation
      #discussion.silverBorderPanel
        .comment-container
          #comments_loading.loader_img{:style => "display:none"}
            = image_tag "loader.gif", :class => 'loader'
          %ul#commentList-30.l-0
            // Comments go here
            
    = render :partial => "comment_form"
           
    
 
  #article_viewer
    .loader_img{:style => "display:none"}
      = image_tag "loader.gif", :class => 'loader'
    %div#no_article
    %div#main_frame.hidden
      = render :partial => "article-iframe"

= render :partial => "sync_modal_window"

app/views/viewers/new.html.erb
<h1>New viewer</h1>

<%= render 'form' %>

<%= link_to 'Back', viewers_path %>

app/views/viewers/show.html.haml
#topbar
  #floatingbar
    = render :partial => "topbar"
#view_content

  // Begin sidebox
  #sidebox
    #header_info
      .logo_wrapper.floatleft
        = link_to image_tag("/images/logo_small.png",  :alt =>  'Goalara.com'), "/"
      .header_comments.floatright
        %strong 
          - if @comments.defined?
            = @comments.size.to_s + ' Σχόλια'
    %div{:style => "clear:both"}
    #conversation
      #discussion.silverBorderPanel
        .comment-container
          %ul#commentList-30.l-0
            // Comments go here
           
    .commentAddForm.clearfix.secondary
      .signed-in
        %label.formItemLabel
          = form_tag(comments_path, :method => "post", :remote => true, :id => "add_comment") do
            %textarea{:cols => "", :name => "body", :rows => ""}
            %input{:name => "commentable_id", :type => "hidden", :value => "#{@article.id if article}" }    
            %input{:name => "user_id", :type => "hidden", :value => "#{current_user.id if current_user}"}
            %input{:name => "commentable_type", :type => "hidden", :value => "Article"}
            - if !user_signed_in?
              .formItemLine.signed-out
                %p.signin
                  = link_to 'Sign in to add comments', new_user_session_remote_path
                  or 
                  = link_to 'Join', user_registration_path
            - else
              %span.button.primary
                %span
                  %input.submit{:name => "submit", :type => "submit", :value => "Submit"}
              %p.charactersUsed
                Characters remaining:
                %em.commentOK 2000
    
          
  #article_viewer
    = render :partial => "article-iframe"
    
#loader_img{:style => "display:none"}
  = image_tag "loader.gif", :class => 'loader'