config/routes.rb
GoalaraCom::Application.routes.draw do
  
  root :to => "articles#index"
  
  devise_for :users, :controllers => {:sessions => 'sessions'}

  resources :users

  resources :viewers

  resources :feeds

  resources :articles

  resources :organizations

  resources :teams
  
  resources :frontpage
  
  resources :comments
  
  resources :votes
  
  get "/comment-vote" => "comments#vote", :as => :comment_vote_path
  
  devise_scope :user do
  
    match "login" => "sessions#sign_in_and_redirect", :as => :new_user_session_remote 
    match "logout" => "sessions#destroy", :as => :destroy_user_session
    match "register" => "devise/registrations#new", :as => :new_user_registration
  end
  
  match "set_teams" => "articles#set_teams"
  
  match "/navigate" => "articles#fetch"
  
  match "/news/:team_name" => "articles#show"
  match "/news" => "articles#show", :as => :navigator
  
  match "/application.manifest" => Rails::Offline
  
  match "/feed" => "articles#rss"
  
  match "/help" => "pages#help"
  
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :fullname, :email, :password, :password_confirmation, :remember_me
  
  has_and_belongs_to_many :roles
  
  acts_as_voter
  
  belongs_to :team
  
  has_many :comments
  
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['extra']['user_hash']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password. 
      User.create(:email => data["email"], :password => Devise.friendly_token[0,20]) 
    end
  end
  
  def role?(role)
      return !!self.roles.find_by_name(role.to_s.camelize)
  end
  
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_user, :only => [:index,:new,:edit]
  before_filter :accessible_roles, :only => [:new, :edit, :show, :update, :create]
  load_and_authorize_resource :only => [:show,:new,:destroy,:edit,:update,:index]
  
  
  
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
    
    @total_comments = Comment.where(:user_id => params[:id]).count
    @total_viewed_articles = Impression.where(:user_id => params[:id]).count('impressionable_id', :distinct => true)
    
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    @title_image = "titles/sign_up.jpg"
    
    respond_to do |format|
      format.html {render :layout => 'pages'} # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= semantic_form_for @user do |f| %>
  <%= f.inputs do %>
  <% end %>

  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>

app/views/users/_loginpanel.html.haml
%fieldset#signin_menu
  #left_panel.floatleft
    %form#signin{:action => "#{new_user_session_remote_path}", :method => "post"}
      %span.title Login with your Goalara.com account
      %label{:for => "username"} Username or email
      %input#username{:name => "username", :tabindex => "4", :title => "username", :type => "text", :value => ""}
        %p
          %label{:for => "password"} Password
          %input#password{:name => "password", :tabindex => "5", :title => "password", :type => "password", :value => ""}
        %p.remember
          %input#signin_submit{:tabindex => "6", :type => "submit", :value => "Sign in"}
            %input#remember{:name => "remember_me", :tabindex => "7", :type => "checkbox", :value => "1"}
              %label{:for => "remember"} Remember me
        %p.forgot
          %a#resend_password_link{:href => "#"} Forgot your password?
        %p.forgot-username
          %a#forgot_username_link{:href => "#", :title => "If you remember your password, try logging in with your email"} Forgot your username?
  #right_panel.floatleft
    %span.title or with your Facebook account
    = link_to image_tag("facebook_alt.png"), user_omniauth_authorize_path(:facebook)
  #bottom_panel.clearfix
    %h2.speech
      I don't have Facebook or an account at Goalara.com
      %a#create_account_link{:href => "#{new_user_registration_path}", :title => "If you remember your password, try logging in with your email"} Create an account at Goalara.com instantly

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show.html.haml
%p#notice= notice
%div.floatleft
  = link_to image_tag(get_user_avatar(@user), :alt => @user.fullname + ' image', :class => "profile"), user_path(@user.id), :target => "_blank", :class => "profile_picture"  

%ul.clearfix.form.disabled{:style => "padding-left: 60px"}
  %li
    %label.label Όνομα:
    %input{:value => "#{@user.fullname}", :readonly => "readonly"}
  %li
    %label.label Ομάδα:
    %input{:value => "#{@user.team ? translate(@user.team.name): ""}", :readonly => "readonly"}  
  %li
    %label.label Έχει σχολιάσει:
    %input{:value => "#{@total_comments} φορές", :readonly => "readonly"}
  %li
    %label.label Έχει διάβασει:
    %input{:value => "#{@total_viewed_articles} άρθρα", :readonly => "readonly"}
      
- if current_user == @user
  = link_to 'Επεξεργασία του λογαριασμού μου', edit_user_registration_path(@user)